### ISSUE TITLE
content for xml file referred at  http://thupv.com/TexturePackerXMLToFNT/#/

### ISSUE THREAD

**Issue by ishaan-puniani** [thupv/convert-texture-packer-xml-to-fnt#1]
Hello, 
Hope you are doing good. 
Is it possible for you to share the content for xml file referred at  http://thupv.com/TexturePackerXMLToFNT/#/  in the readme.md as this url is not working for me.

--
Thanks

**Comment by thupv** [comment]
Hi,
thank you, you can use this URL for now: https://thupv.github.io/convert-texture-packer-xml-to-fnt
